name: MacOSX Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: false
        default: 'v1.15.0'
      label:
        description: 'Additional label for release'
        required: false
        default: ''
      prerelease:
        description: 'Mark Release as Pre-Release'
        required: false
        default: 'false'

jobs:
  build:
    strategy:
      matrix:
        os: [ 'macos-13' ]
        python-version: [ '3.10', '3.11' ]
  
    runs-on: ${{ matrix.os }}

    name: ${{ github.event.inputs.tag }} python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      # install prerequisites
      - name: Preqrequisites
        run: |
          arch -arm64 brew install cmake pkg-config
          brew install wget git git-lfs
          arch -arm64 brew install protobuf
          python -m pip install --upgrade pip

      # run build command
      - name: Build onnxruntime-silicon
        run: |
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          ./build-macos.sh
          ls -la dist
          
      # upload dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: "macosx-${{ github.event.inputs.tag }}${{ github.event.inputs.label }}"
          release_name: "onnxruntime-silicon ${{ github.event.inputs.tag }}${{ github.event.inputs.label }}"
          body: "Prebuilt onnxruntime-silicon wheel packages for MacOS version ${{ github.event.inputs.tag }}."
          overwrite: true
          file_glob: true
          # prerelease: ${{ github.event.inputs.prerelease }}
